version: "3.9"
services:
  db:
    image: postgres:16
    container_name: makeup-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: makeup_user
      POSTGRES_PASSWORD: makeup_password
      POSTGRES_DB: makeup_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
